# _config.yml
title: GTRADES-AXIS™
description: Professional Trading Framework
baseurl: ""
url: "https://gtradesaxis.com"
permalink: /:title/
exclude:
  - README.md
  - .gitignore
  - .github/
  - node_modules/